<?php
/**
 * Created by PhpStorm.
 * User: LYK
 * Date: 2015/6/1
 * Time: 16:26
 */
namespace frontend\models;

use yii\db\ActiveRecord;

class Country extends ActiveRecord{
    public static function tableName()
    {
        return "country"; // TODO: Change the autogenerated stub
    }

}